version: '3'
services: 
  sqldatabase:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
  
  flask-app:
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./backend/app_package:/app/app_package
    ports: 
      - "5000:5000"

  react-app:
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    volumes: 
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development


